name: Run Android Emulator in GitHub Actions

on:
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          disable-animations: false
          # هنا زودنا الوقت اللي بنستناه عشان المحاكي يقوم براحته
          ram-size: 2048M
          cpu-cores: 2
          script: |
            echo "Waiting for emulator to fully boot up..."
            # أمر ذكي يخلي الـ script يلف و يستنى لحد ما الـ boot يخلص فعلاً
            adb wait-for-device
            
            # حلقة تكرارية تستنى لحد ما الـ boot_completed تدي 1
            while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
              echo "Still booting..."
              sleep 5
            done
            
            echo "Emulator is fully booted and ready!"
            adb shell input keyevent 82
